import React,{createContext,useContext,useEffect,useState} from 'react';
import {DayMenuSchedule,PackageType} from '../types';
import {DEFAULT_BANNERS,DEFAULT_MENUS,DEFAULT_PANELS,DEFAULT_PAYMENT,DEFAULT_PRICING,DEFAULT_REGISTRATION_FIELDS,DEFAULT_ROLES,DEFAULT_SITE_SETTINGS,PricingConfig,BannerConfig,RegistrationFieldConfig} from './cmsDefaults';
import {isSupabaseConfigured,supabaseDelete,supabaseSelect,supabaseUpsert} from './supabaseRest';
export interface PanelConfig{id:string;name:string;sort_order:number;active:boolean}
export interface RoleConfig{id:string;name:string;active:boolean}
export interface PermissionConfig{role_id:string;panel_id:string;can_read:boolean;can_write:boolean;can_add:boolean;can_delete:boolean}
export interface AdminUserConfig{user_id:string;username?:string;email:string;role_id:string;active:boolean}
export interface PaymentConfig{bankName:string;accountHolder:string;accountNumber:string;ifscCode:string;accountType:string;authorizedSignatory:string;upiId:string;phone:string;qrUrl?:string}
interface CmsContextType{connected:boolean;loading:boolean;error:string;siteSettings:Record<string,string>;pricing:PricingConfig;banners:BannerConfig[];payment:PaymentConfig;registrationFields:RegistrationFieldConfig[];menus:Record<PackageType,DayMenuSchedule[]>;panels:PanelConfig[];roles:RoleConfig[];permissions:PermissionConfig[];adminUsers:AdminUserConfig[];refresh:()=>Promise<void>;initializeDefaults:()=>Promise<void>;updateSetting:(key:string,value:string)=>Promise<void>;updatePricing:(values:Partial<PricingConfig>)=>Promise<void>;saveBanner:(b:BannerConfig)=>Promise<void>;deleteBanner:(id:string)=>Promise<void>;savePayment:(v:PaymentConfig)=>Promise<void>;saveRegistrationField:(f:RegistrationFieldConfig)=>Promise<void>;deleteRegistrationField:(id:string)=>Promise<void>;saveMenu:(p:PackageType,m:DayMenuSchedule[])=>Promise<void>;savePanel:(p:PanelConfig)=>Promise<void>;deletePanel:(id:string)=>Promise<void>;saveRole:(r:RoleConfig)=>Promise<void>;deleteRole:(id:string)=>Promise<void>;savePermission:(p:PermissionConfig)=>Promise<void>;saveAdminUser:(u:AdminUserConfig)=>Promise<void>;deleteAdminUser:(id:string)=>Promise<void>;hasPermission:(r:string,p:string,a:'read'|'write'|'add'|'delete')=>boolean}
const CmsContext=createContext<CmsContextType|undefined>(undefined); const CACHE='bmb_cms_cache_v2';
const readCache=()=>{try{return JSON.parse(localStorage.getItem(CACHE)||'null')}catch{return null}}; const writeCache=(v:any)=>{try{localStorage.setItem(CACHE,JSON.stringify(v))}catch{}};
const record=(rows:any[])=>rows.reduce((a,r)=>(a[r.key]=typeof r.value==='string'?r.value:JSON.stringify(r.value),a),{} as Record<string,string>);
export const CmsProvider:React.FC<{children:React.ReactNode}>=({children})=>{const[loading,setLoading]=useState(false),[error,setError]=useState(''),[siteSettings,setSiteSettings]=useState(DEFAULT_SITE_SETTINGS),[pricing,setPricing]=useState(DEFAULT_PRICING),[banners,setBanners]=useState(DEFAULT_BANNERS),[payment,setPayment]=useState<PaymentConfig>(DEFAULT_PAYMENT),[registrationFields,setRegistrationFields]=useState(DEFAULT_REGISTRATION_FIELDS),[menus,setMenus]=useState(DEFAULT_MENUS),[panels,setPanels]=useState<PanelConfig[]>(DEFAULT_PANELS),[roles,setRoles]=useState<RoleConfig[]>(DEFAULT_ROLES),[permissions,setPermissions]=useState<PermissionConfig[]>([]),[adminUsers,setAdminUsers]=useState<AdminUserConfig[]>([]);
 const refresh=async()=>{setLoading(true);setError('');if(!isSupabaseConfigured){const c=readCache();if(c){setSiteSettings(c.siteSettings||DEFAULT_SITE_SETTINGS);setPricing(c.pricing||DEFAULT_PRICING);setBanners(c.banners||DEFAULT_BANNERS);setPayment(c.payment||DEFAULT_PAYMENT);setRegistrationFields(c.registrationFields||DEFAULT_REGISTRATION_FIELDS);setMenus(c.menus||DEFAULT_MENUS);setPanels(c.panels||DEFAULT_PANELS);setRoles(c.roles||DEFAULT_ROLES);setPermissions(c.permissions||[]);setAdminUsers(c.adminUsers||[])}setLoading(false);return}try{const[s,p,b,pay,f,m,pa,r,pe,u]=await Promise.all([supabaseSelect<any>('bmb_settings','select=key,value'),supabaseSelect<any>('bmb_pricing','select=key,value'),supabaseSelect<BannerConfig>('bmb_banners','select=*&order=sort_order.asc'),supabaseSelect<any>('bmb_payment_settings','select=*&limit=1'),supabaseSelect<RegistrationFieldConfig>('bmb_registration_fields','select=*&order=sort_order.asc'),supabaseSelect<any>('bmb_menus','select=*'),supabaseSelect<PanelConfig>('bmb_panels','select=*&order=sort_order.asc'),supabaseSelect<RoleConfig>('bmb_roles','select=*'),supabaseSelect<PermissionConfig>('bmb_permissions','select=*'),supabaseSelect<AdminUserConfig>('bmb_admin_users','select=user_id,username,email,role_id,active')]);const ns={...DEFAULT_SITE_SETTINGS,...record(s)},np={...DEFAULT_PRICING,...Object.fromEntries(p.map((x:any)=>[x.key,Number(x.value)]))},nm=m.length?{...DEFAULT_MENUS,...Object.fromEntries(m.map((x:any)=>[x.package_type,x.menu]))}:DEFAULT_MENUS;setSiteSettings(ns);setPricing(np);setBanners(b.length?b:DEFAULT_BANNERS);if(pay[0])setPayment({bankName:pay[0].bank_name,accountHolder:pay[0].account_holder,accountNumber:pay[0].account_number,ifscCode:pay[0].ifsc_code,accountType:pay[0].account_type,authorizedSignatory:pay[0].authorized_signatory,upiId:pay[0].upi_id,phone:pay[0].phone,qrUrl:pay[0].qr_url});setRegistrationFields(f.length?f:DEFAULT_REGISTRATION_FIELDS);setMenus(nm);setPanels(pa.length?pa:DEFAULT_PANELS);setRoles(r.length?r:DEFAULT_ROLES);setPermissions(pe);setAdminUsers(u);writeCache({siteSettings:ns,pricing:np,banners:b.length?b:DEFAULT_BANNERS,payment:pay[0]?{bankName:pay[0].bank_name,accountHolder:pay[0].account_holder,accountNumber:pay[0].account_number,ifscCode:pay[0].ifsc_code,accountType:pay[0].account_type,authorizedSignatory:pay[0].authorized_signatory,upiId:pay[0].upi_id,phone:pay[0].phone,qrUrl:pay[0].qr_url}:DEFAULT_PAYMENT,registrationFields:f.length?f:DEFAULT_REGISTRATION_FIELDS,menus:nm,panels:pa.length?pa:DEFAULT_PANELS,roles:r.length?r:DEFAULT_ROLES,permissions:pe,adminUsers:u})}catch(e){setError(e instanceof Error?e.message:'Unable to load central CMS')}finally{setLoading(false)}};
 const initializeDefaults=async()=>{await refresh()}; useEffect(()=>{void initializeDefaults()},[]); useEffect(()=>{if(!isSupabaseConfigured)return;const id=window.setInterval(()=>void refresh(),15000);return()=>window.clearInterval(id)},[]);
 const updateSetting=async(k:string,v:string)=>{await supabaseUpsert('bmb_settings',{key:k,value:v});await refresh()}; const updatePricing=async(v:Partial<PricingConfig>)=>{await supabaseUpsert('bmb_pricing',Object.entries(v).map(([key,value])=>({key,value})));await refresh()}; const saveBanner=async(b:BannerConfig)=>{await supabaseUpsert('bmb_banners',b);await refresh()}; const deleteBanner=async(id:string)=>{await supabaseDelete('bmb_banners',`id=eq.${encodeURIComponent(id)}`);await refresh()}; const savePayment=async(v:PaymentConfig)=>{await supabaseUpsert('bmb_payment_settings',{id:'default',bank_name:v.bankName,account_holder:v.accountHolder,account_number:v.accountNumber,ifsc_code:v.ifscCode,account_type:v.accountType,authorized_signatory:v.authorizedSignatory,upi_id:v.upiId,phone:v.phone,qr_url:v.qrUrl||''});await refresh()}; const saveRegistrationField=async(f:RegistrationFieldConfig)=>{await supabaseUpsert('bmb_registration_fields',f);await refresh()}; const deleteRegistrationField=async(id:string)=>{await supabaseDelete('bmb_registration_fields',`id=eq.${encodeURIComponent(id)}`);await refresh()}; const saveMenu=async(p:PackageType,m:DayMenuSchedule[])=>{await supabaseUpsert('bmb_menus',{package_type:p,menu:m});await refresh()}; const savePanel=async(p:PanelConfig)=>{await supabaseUpsert('bmb_panels',p);await refresh()}; const deletePanel=async(id:string)=>{await supabaseDelete('bmb_panels',`id=eq.${encodeURIComponent(id)}`);await refresh()}; const saveRole=async(r:RoleConfig)=>{await supabaseUpsert('bmb_roles',r);await refresh()}; const deleteRole=async(id:string)=>{await supabaseDelete('bmb_roles',`id=eq.${encodeURIComponent(id)}`);await refresh()}; const savePermission=async(p:PermissionConfig)=>{await supabaseUpsert('bmb_permissions',p);await refresh()}; const saveAdminUser=async(u:AdminUserConfig)=>{await supabasePatch('bmb_admin_users',`user_id=eq.${encodeURIComponent(u.user_id)}`,{username:u.username?.trim().toLowerCase(),role_id:u.role_id,active:u.active,email:u.email});await refresh()}; const deleteAdminUser=async(id:string)=>{await supabasePatch('bmb_admin_users',`user_id=eq.${encodeURIComponent(id)}`,{active:false});await refresh()}; const hasPermission=(r:string,p:string,a:'read'|'write'|'add'|'delete')=>{const x=permissions.find(i=>i.role_id===r&&i.panel_id===p);return Boolean(x?.[a==='read'?'can_read':a==='write'?'can_write':a==='add'?'can_add':'can_delete'])};
 return <CmsContext.Provider value={{connected:isSupabaseConfigured,loading,error,siteSettings,pricing,banners,payment,registrationFields,menus,panels,roles,permissions,adminUsers,refresh,initializeDefaults,updateSetting,updatePricing,saveBanner,deleteBanner,savePayment,saveRegistrationField,deleteRegistrationField,saveMenu,savePanel,deletePanel,saveRole,deleteRole,savePermission,saveAdminUser,deleteAdminUser,hasPermission}}>{children}</CmsContext.Provider>};
export const useCms=()=>{const c=useContext(CmsContext);if(!c)throw new Error('useCms must be used within CmsProvider');return c;};
