import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { DayMenuSchedule, PackageType } from '../types';
import { DEFAULT_BANNERS, DEFAULT_MENUS, DEFAULT_PANELS, DEFAULT_PAYMENT, DEFAULT_PRICING, DEFAULT_REGISTRATION_FIELDS, DEFAULT_ROLES, DEFAULT_SITE_SETTINGS, PricingConfig, BannerConfig, RegistrationFieldConfig } from './cmsDefaults';
import { isSupabaseConfigured, supabaseDelete, supabaseSelect, supabaseUpsert } from './supabaseRest';
import { subscribeToSupabaseChanges } from './supabaseRealtime';

export interface PanelConfig { id: string; name: string; sort_order: number; active: boolean; }
export interface RoleConfig { id: string; name: string; active: boolean; }
export interface PermissionConfig { role_id: string; panel_id: string; can_read: boolean; can_write: boolean; can_add: boolean; can_delete: boolean; }
export interface AdminUserConfig { user_id: string; username?: string; email: string; role_id: string; active: boolean; }
export interface PaymentConfig { bankName: string; accountHolder: string; accountNumber: string; ifscCode: string; accountType: string; authorizedSignatory: string; upiId: string; phone: string; qrUrl?: string; }

interface CmsContextType {
  connected: boolean; loading: boolean; error: string; siteSettings: Record<string, string>; pricing: PricingConfig; banners: BannerConfig[]; payment: PaymentConfig;
  registrationFields: RegistrationFieldConfig[]; menus: Record<PackageType, DayMenuSchedule[]>; panels: PanelConfig[]; roles: RoleConfig[]; permissions: PermissionConfig[]; adminUsers: AdminUserConfig[];
  refresh: () => Promise<void>; initializeDefaults: () => Promise<void>; updateSetting: (key: string, value: string) => Promise<void>; updatePricing: (values: Partial<PricingConfig>) => Promise<void>;
  saveBanner: (banner: BannerConfig) => Promise<void>; deleteBanner: (id: string) => Promise<void>; savePayment: (payment: PaymentConfig) => Promise<void>; saveRegistrationField: (field: RegistrationFieldConfig) => Promise<void>; deleteRegistrationField: (id: string) => Promise<void>;
  saveMenu: (packageType: PackageType, menu: DayMenuSchedule[]) => Promise<void>; savePanel: (panel: PanelConfig) => Promise<void>; deletePanel: (id: string) => Promise<void>; saveRole: (role: RoleConfig) => Promise<void>; deleteRole: (id: string) => Promise<void>;
  savePermission: (permission: PermissionConfig) => Promise<void>; saveAdminUser: (user: AdminUserConfig) => Promise<void>; deleteAdminUser: (userId: string) => Promise<void>; hasPermission: (roleId: string, panelId: string, action: 'read' | 'write' | 'add' | 'delete') => boolean;
}

const CmsContext = createContext<CmsContextType | undefined>(undefined);
const LOCAL_CMS_KEY = 'bmb_cms_cache_v2';
const readLocalCms = (): any | null => { try { return JSON.parse(localStorage.getItem(LOCAL_CMS_KEY) || 'null'); } catch { return null; } };
const writeLocalCms = (data: any) => { try { localStorage.setItem(LOCAL_CMS_KEY, JSON.stringify(data)); } catch {} };
const asRecord = (rows: Array<{ key: string; value: unknown }>) => rows.reduce<Record<string, string>>((acc, row) => { acc[row.key] = typeof row.value === 'string' ? row.value : JSON.stringify(row.value); return acc; }, {});
const normalizeUsername = (value: string | undefined, email: string, roleId: string) => { const candidate = (value || '').trim().toLowerCase().replace(/[^a-z0-9._-]/g, '').slice(0, 32); if (candidate.length >= 3) return candidate; const fromEmail = email.split('@')[0].trim().toLowerCase().replace(/[^a-z0-9._-]/g, '').slice(0, 32); if (fromEmail.length >= 3) return fromEmail; return roleId === 'ceo-director' ? 'dadmin' : roleId.replace(/[^a-z0-9._-]/g, '').slice(0, 32); };

export const CmsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [loading, setLoading] = useState(false), [error, setError] = useState('');
  const [siteSettings, setSiteSettings] = useState(DEFAULT_SITE_SETTINGS), [pricing, setPricing] = useState(DEFAULT_PRICING), [banners, setBanners] = useState(DEFAULT_BANNERS);
  const [payment, setPayment] = useState<PaymentConfig>(DEFAULT_PAYMENT), [registrationFields, setRegistrationFields] = useState(DEFAULT_REGISTRATION_FIELDS), [menus, setMenus] = useState(DEFAULT_MENUS);
  const [panels, setPanels] = useState<PanelConfig[]>(DEFAULT_PANELS), [roles, setRoles] = useState<RoleConfig[]>(DEFAULT_ROLES), [permissions, setPermissions] = useState<PermissionConfig[]>([]), [adminUsers, setAdminUsers] = useState<AdminUserConfig[]>([]);
  const initializeDefaults = async () => { if (!isSupabaseConfigured) return; await refresh(); };
  const refresh = async () => {
    setLoading(true); setError('');
    if (!isSupabaseConfigured) { const cached = readLocalCms(); if (cached) { setSiteSettings({ ...DEFAULT_SITE_SETTINGS, ...(cached.siteSettings || {}) }); setPricing({ ...DEFAULT_PRICING, ...(cached.pricing || {}) }); setBanners(cached.banners?.length ? cached.banners : DEFAULT_BANNERS); setPayment(cached.payment || DEFAULT_PAYMENT); setRegistrationFields(cached.registrationFields?.length ? cached.registrationFields : DEFAULT_REGISTRATION_FIELDS); setMenus(cached.menus || DEFAULT_MENUS); setPanels(cached.panels?.length ? cached.panels : DEFAULT_PANELS); setRoles(cached.roles?.length ? cached.roles : DEFAULT_ROLES); setPermissions(cached.permissions || []); setAdminUsers(cached.adminUsers || []); } setLoading(false); return; }
    try {
      const [settingsRows, pricingRows, bannerRows, paymentRows, fieldRows, menuRows, panelRows, roleRows, permissionRows, adminUserRows] = await Promise.all([
        supabaseSelect<{ key: string; value: string }>('bmb_settings', 'select=key,value'), supabaseSelect<{ key: string; value: number }>('bmb_pricing', 'select=key,value'), supabaseSelect<BannerConfig>('bmb_banners', 'select=*&order=sort_order.asc'), supabaseSelect<any>('bmb_payment_settings', 'select=*&limit=1'),
        supabaseSelect<RegistrationFieldConfig>('bmb_registration_fields', 'select=*&order=sort_order.asc'), supabaseSelect<{ package_type: PackageType; menu: DayMenuSchedule[] }>('bmb_menus', 'select=*'), supabaseSelect<PanelConfig>('bmb_panels', 'select=*&order=sort_order.asc'), supabaseSelect<RoleConfig>('bmb_roles', 'select=*'), supabaseSelect<PermissionConfig>('bmb_permissions', 'select=*'), supabaseSelect<AdminUserConfig>('bmb_admin_users', 'select=user_id,username,email,role_id,active')
      ]);
      const nextSettings = { ...DEFAULT_SITE_SETTINGS, ...asRecord(settingsRows) }, nextPricing = { ...DEFAULT_PRICING, ...Object.fromEntries(pricingRows.map(r => [r.key, Number(r.value)])) }, nextMenus = menuRows.length ? { ...DEFAULT_MENUS, ...Object.fromEntries(menuRows.map(r => [r.package_type, r.menu])) } : DEFAULT_MENUS;
      setSiteSettings(nextSettings); setPricing(nextPricing); setBanners(bannerRows.length ? bannerRows : DEFAULT_BANNERS); if (paymentRows[0]) setPayment({ bankName: paymentRows[0].bank_name, accountHolder: paymentRows[0].account_holder, accountNumber: paymentRows[0].account_number, ifscCode: paymentRows[0].ifsc_code, accountType: paymentRows[0].account_type, authorizedSignatory: paymentRows[0].authorized_signatory, upiId: paymentRows[0].upi_id, phone: paymentRows[0].phone, qrUrl: paymentRows[0].qr_url }); if (fieldRows.length) setRegistrationFields(fieldRows); setMenus(nextMenus); if (panelRows.length) setPanels(panelRows); if (roleRows.length) setRoles(roleRows); setPermissions(permissionRows); setAdminUsers(adminUserRows);
      writeLocalCms({ siteSettings: nextSettings, pricing: nextPricing, banners: bannerRows.length ? bannerRows : DEFAULT_BANNERS, payment: paymentRows[0] ? { bankName: paymentRows[0].bank_name, accountHolder: paymentRows[0].account_holder, accountNumber: paymentRows[0].account_number, ifscCode: paymentRows[0].ifsc_code, accountType: paymentRows[0].account_type, authorizedSignatory: paymentRows[0].authorizedSignatory, upiId: paymentRows[0].upi_id, phone: paymentRows[0].phone, qrUrl: paymentRows[0].qr_url } : DEFAULT_PAYMENT, registrationFields: fieldRows.length ? fieldRows : DEFAULT_REGISTRATION_FIELDS, menus: nextMenus, panels: panelRows.length ? panelRows : DEFAULT_PANELS, roles: roleRows.length ? roleRows : DEFAULT_ROLES, permissions: permissionRows, adminUsers: adminUserRows });
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load central settings'); } finally { setLoading(false); }
  };
  useEffect(() => { void initializeDefaults(); }, []);
  useEffect(() => { if (!isSupabaseConfigured) return; const tables=['bmb_settings','bmb_pricing','bmb_banners','bmb_menus','bmb_registration_fields','bmb_payment_settings','bmb_panels','bmb_roles','bmb_permissions','bmb_admin_users']; const unsubscribe=subscribeToSupabaseChanges(tables,()=>{void refresh();}); const fallback=window.setInterval(()=>void refresh(),60000); return()=>{unsubscribe();window.clearInterval(fallback);}; }, []);
  const updateSetting = async (key: string, value: string) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_settings',{key,value}); const next={...siteSettings,[key]:value}; setSiteSettings(next); writeLocalCms({...(readLocalCms()||{}),siteSettings:next}); };
  const updatePricing = async (values: Partial<PricingConfig>) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_pricing',Object.entries(values).map(([key,value])=>({key,value}))); const next={...pricing,...values}; setPricing(next); writeLocalCms({...(readLocalCms()||{}),pricing:next}); };
  const saveBanner = async (banner: BannerConfig) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_banners',banner); const next=[...banners.filter(b=>b.id!==banner.id),banner].sort((a,b)=>a.sort_order-b.sort_order); setBanners(next); writeLocalCms({...(readLocalCms()||{}),banners:next}); };
  const deleteBanner = async (id:string) => { if(isSupabaseConfigured) await supabaseDelete('bmb_banners',`id=eq.${encodeURIComponent(id)}`); const next=banners.filter(b=>b.id!==id); setBanners(next); writeLocalCms({...(readLocalCms()||{}),banners:next}); };
  const savePayment = async (value:PaymentConfig) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_payment_settings',{id:'default',bank_name:value.bankName,account_holder:value.accountHolder,account_number:value.accountNumber,ifsc_code:value.ifscCode,account_type:value.accountType,authorized_signatory:value.authorizedSignatory,upi_id:value.upiId,phone:value.phone,qr_url:value.qrUrl||''}); setPayment(value); writeLocalCms({...(readLocalCms()||{}),payment:value}); };
  const saveRegistrationField = async (field:RegistrationFieldConfig) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_registration_fields',field); const next=[...registrationFields.filter(f=>f.id!==field.id),field].sort((a,b)=>a.sort_order-b.sort_order); setRegistrationFields(next); writeLocalCms({...(readLocalCms()||{}),registrationFields:next}); };
  const deleteRegistrationField = async (id:string) => { if(isSupabaseConfigured) await supabaseDelete('bmb_registration_fields',`id=eq.${encodeURIComponent(id)}`); const next=registrationFields.filter(f=>f.id!==id); setRegistrationFields(next); writeLocalCms({...(readLocalCms()||{}),registrationFields:next}); };
  const saveMenu = async (packageType:PackageType,menu:DayMenuSchedule[]) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_menus',{package_type:packageType,menu}); const next={...menus,[packageType]:menu}; setMenus(next); writeLocalCms({...(readLocalCms()||{}),menus:next}); };
  const savePanel = async (panel:PanelConfig) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_panels',panel); const next=[...panels.filter(p=>p.id!==panel.id),panel].sort((a,b)=>a.sort_order-b.sort_order); setPanels(next); writeLocalCms({...(readLocalCms()||{}),panels:next}); };
  const deletePanel = async (id:string) => { if(isSupabaseConfigured) await supabaseDelete('bmb_panels',`id=eq.${encodeURIComponent(id)}`); const next=panels.filter(p=>p.id!==id); setPanels(next); writeLocalCms({...(readLocalCms()||{}),panels:next}); };
  const saveRole = async (role:RoleConfig) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_roles',role); const next=[...roles.filter(r=>r.id!==role.id),role]; setRoles(next); writeLocalCms({...(readLocalCms()||{}),roles:next}); };
  const deleteRole = async (id:string) => { if(isSupabaseConfigured) await supabaseDelete('bmb_roles',`id=eq.${encodeURIComponent(id)}`); const next=roles.filter(r=>r.id!==id); setRoles(next); writeLocalCms({...(readLocalCms()||{}),roles:next}); };
  const savePermission = async (permission:PermissionConfig) => { if(isSupabaseConfigured) await supabaseUpsert('bmb_permissions',permission); const next=[...permissions.filter(p=>!(p.role_id===permission.role_id&&p.panel_id===permission.panel_id)),permission]; setPermissions(next); writeLocalCms({...(readLocalCms()||{}),permissions:next}); };
  const saveAdminUser = async (user:AdminUserConfig) => { const username=normalizeUsername(user.username,user.email,user.role_id); const normalized={...user,username}; if(isSupabaseConfigured) await supabaseUpsert('bmb_admin_users',normalized); const next=[...adminUsers.filter(u=>u.user_id!==user.user_id&&u.username!==username),normalized]; setAdminUsers(next); writeLocalCms({...(readLocalCms()||{}),adminUsers:next}); };
  const deleteAdminUser = async (userId:string) => { if(isSupabaseConfigured) await supabaseDelete('bmb_admin_users',`user_id=eq.${encodeURIComponent(userId)}`); const next=adminUsers.filter(u=>u.user_id!==userId); setAdminUsers(next); writeLocalCms({...(readLocalCms()||{}),adminUsers:next}); };
  const hasPermission = (roleId:string,panelId:string,action:'read'|'write'|'add'|'delete') => { if(roleId==='ceo-director'||roleId==='d_admin') return true; const p=permissions.find(x=>x.role_id===roleId&&x.panel_id===panelId); return Boolean(p&&({read:p.can_read,write:p.can_write,add:p.can_add,delete:p.can_delete}[action])); };
  const value=useMemo(()=>({connected:isSupabaseConfigured,loading,error,siteSettings,pricing,banners,payment,registrationFields,menus,panels,roles,permissions,adminUsers,refresh,initializeDefaults,updateSetting,updatePricing,saveBanner,deleteBanner,savePayment,saveRegistrationField,deleteRegistrationField,saveMenu,savePanel,deletePanel,saveRole,deleteRole,savePermission,saveAdminUser,deleteAdminUser,hasPermission}),[loading,error,siteSettings,pricing,banners,payment,registrationFields,menus,panels,roles,permissions,adminUsers]);
  return <CmsContext.Provider value={value}>{children}</CmsContext.Provider>;
};
export const useCms=()=>{const context=useContext(CmsContext);if(!context)throw new Error('useCms must be used within a CmsProvider');return context;};
