import React, { useMemo, useState } from 'react';
import { Printer, Plus, Trash2 } from 'lucide-react';
const input='w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm';
type Line={description:string,qty:number,rate:number};
export const GSTBillingPanel:React.FC=()=>{
 const [gstInvoice,setGstInvoice]=useState(true); const [gstin,setGstin]=useState(''); const [customer,setCustomer]=useState(''); const [address,setAddress]=useState(''); const [invoiceNo,setInvoiceNo]=useState(`BMB-${new Date().getFullYear()}-${Date.now().toString().slice(-5)}`); const [gstRate,setGstRate]=useState(18); const [lines,setLines]=useState<Line[]>([{description:'Tiffin / Meal Service',qty:1,rate:0}]);
 const subtotal=useMemo(()=>lines.reduce((s,x)=>s+x.qty*x.rate,0),[lines]); const tax=gstInvoice?subtotal*gstRate/100:0; const total=subtotal+tax;
 const print=()=>{const html=`<!doctype html><html><head><title>${invoiceNo}</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:8px;text-align:left}.right{text-align:right}</style></head><body><h1>Bring My Bite</h1><p>SHREE FOODS</p><h2>${gstInvoice?'TAX INVOICE':'BILL / RECEIPT'}</h2><p><b>Invoice:</b> ${invoiceNo}<br><b>Customer:</b> ${customer}<br><b>Address:</b> ${address}${gstInvoice?`<br><b>GSTIN:</b> ${gstin||'N/A'}`:''}</p><table><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>${lines.map(x=>`<tr><td>${x.description}</td><td>${x.qty}</td><td>₹${x.rate.toFixed(2)}</td><td>₹${(x.qty*x.rate).toFixed(2)}</td></tr>`).join('')}</table><p class="right">Subtotal: ₹${subtotal.toFixed(2)}<br>${gstInvoice?`GST (${gstRate}%): ₹${tax.toFixed(2)}<br>`:''}<b>Total: ₹${total.toFixed(2)}</b></p><p>Thank you — Bring My Bite | +91 9315075165</p><script>window.print()<\/script></body></html>`; const w=window.open('','_blank'); if(w){w.document.write(html);w.document.close();}};
 return <div className="bg-white rounded-2xl border border-gray-200 p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-[#124E33]">GST / Corporate Billing</h2><p className="text-sm text-gray-500">Use GST invoice for offices/contracts (15/20 tiffins etc.) or switch it off for normal non-GST bills.</p></div><button onClick={print} className="px-4 py-2.5 rounded-xl bg-[#124E33] text-white font-black flex gap-2"><Printer className="w-4 h-4"/>Print Bill</button></div>
 <div className="flex gap-2"><button onClick={()=>setGstInvoice(false)} className={`px-3 py-2 rounded-xl text-xs font-black ${!gstInvoice?'bg-gray-900 text-white':'bg-gray-100'}`}>Normal Bill</button><button onClick={()=>setGstInvoice(true)} className={`px-3 py-2 rounded-xl text-xs font-black ${gstInvoice?'bg-emerald-700 text-white':'bg-gray-100'}`}>GST Tax Invoice</button></div>
 <div className="grid md:grid-cols-2 gap-3"><input className={input} value={invoiceNo} onChange={e=>setInvoiceNo(e.target.value)} placeholder="Invoice number"/><input className={input} value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Office / Customer name"/><input className={input} value={address} onChange={e=>setAddress(e.target.value)} placeholder="Billing address"/>{gstInvoice&&<input className={input} value={gstin} onChange={e=>setGstin(e.target.value)} placeholder="Customer GSTIN"/>}{gstInvoice&&<input className={input} type="number" value={gstRate} onChange={e=>setGstRate(Number(e.target.value))} placeholder="GST %"/>}</div>
 <div className="space-y-2">{lines.map((l,i)=><div key={i} className="grid md:grid-cols-[2fr_100px_140px_40px] gap-2"><input className={input} value={l.description} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><input className={input} type="number" value={l.qty} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,qty:Number(e.target.value)}:x))}/><input className={input} type="number" value={l.rate} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,rate:Number(e.target.value)}:x))}/><button onClick={()=>setLines(lines.filter((_,j)=>j!==i))} className="text-rose-600"><Trash2 className="w-4 h-4"/></button></div>)}</div>
 <button onClick={()=>setLines([...lines,{description:'Additional service',qty:1,rate:0}])} className="px-3 py-2 rounded-xl bg-amber-100 text-amber-900 text-xs font-black flex gap-2"><Plus className="w-4 h-4"/>Add Line</button>
 <div className="text-right bg-gray-50 rounded-xl p-4 font-bold">Subtotal ₹{subtotal.toFixed(2)} {gstInvoice&&<>• GST ₹{tax.toFixed(2)}</>} <span className="text-xl font-black text-[#124E33]">• Total ₹{total.toFixed(2)}</span></div></div>;
};
