import React,{useEffect,useMemo,useState} from 'react';
import {supabaseDelete,supabaseInsert,supabaseSelect} from '../../cms/supabaseRest';
import {ChefHat,Trash2,Plus,Calculator,AlertTriangle} from 'lucide-react';
import {suggestedIngredientsForThali} from '../../utils/inventorySuggestions.mjs';
export const UNITS=['kg','grams','packets','pieces','liters','boxes'];
export function InventoryRecipeTools({menuByPackage,trays,inventory=[]}:{menuByPackage:Record<string,any[]>;trays:Record<string,number>;inventory?:any[]}){
 const [rows,setRows]=useState<any[]>([]),[pkg,setPkg]=useState('VEG CLASSIC'),[meal,setMeal]=useState('lunch'),[dish,setDish]=useState(''),[ing,setIng]=useState(''),[qty,setQty]=useState(''),[unit,setUnit]=useState('grams'),[msg,setMsg]=useState('');
 const [suggested,setSuggested]=useState<any[]>([]),[suggestionThalis,setSuggestionThalis]=useState(String(trays['VEG CLASSIC']||1));
 const load=async()=>{try{setRows(await supabaseSelect<any>('bmb_recipe_ingredients','select=*&active=eq.true&order=package_type,meal,dish_name,ingredient_name'))}catch(e){setMsg(e instanceof Error?e.message:'Recipe load failed')}};useEffect(()=>{void load()},[]);
 const dishes=useMemo(()=>{const s=new Set<string>();(menuByPackage[pkg]||[]).forEach((d:any)=>{const m=meal==='lunch'?d.lunch:d.dinner;if(m)[m.dal,m.dryVeg,m.gravyOrNonVeg,m.rice,m.foilPacked,m.extras].forEach((x:any)=>x&&s.add(String(x))) });return [...s]},[menuByPackage,pkg,meal]);useEffect(()=>{if(!dishes.includes(dish))setDish(dishes[0]||'')},[dishes,dish]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();const n=Number(qty);if(!dish||!ing.trim()||!Number.isFinite(n)||n<=0)return;try{await supabaseInsert('bmb_recipe_ingredients',{id:`REC-${Date.now()}`,package_type:pkg,meal,dish_name:dish,ingredient_name:ing.trim(),quantity_per_tray:n,unit,active:true,updated_at:new Date().toISOString()});setIng('');setQty('');setMsg('Recipe saved');await load()}catch(e){setMsg(e instanceof Error?e.message:'Recipe save failed')}};
 const remove=async(id:string)=>{try{await supabaseDelete('bmb_recipe_ingredients',`id=eq.${encodeURIComponent(id)}`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Delete failed')}};
 const generateSuggestions=()=>setSuggested(suggestedIngredientsForThali(pkg,meal,Number(suggestionThalis)));
 const findStock=(name:string)=>inventory.find(i=>i.name.trim().toLowerCase()===name.trim().toLowerCase());
 const list=rows.filter(r=>r.package_type===pkg&&r.meal===meal);return <div className="space-y-4">
  <div className="bg-white border rounded-2xl p-5"><h2 className="font-black text-sm uppercase flex gap-2"><ChefHat/> Recipe Standard / Tray</h2><p className="text-xs text-gray-500">Enter the actual quantity used for one tray. Saved standards are optional; suggested quantities can be used when a recipe is not configured.</p><form onSubmit={add} className="grid grid-cols-2 md:grid-cols-6 gap-2 mt-3 text-xs"><select value={pkg} onChange={e=>setPkg(e.target.value)} className="p-2 border rounded"><option>VEG CLASSIC</option><option>EGG DELIGHT</option><option>NON-VEG CLUB</option></select><select value={meal} onChange={e=>setMeal(e.target.value)} className="p-2 border rounded"><option>lunch</option><option>dinner</option></select><select value={dish} onChange={e=>setDish(e.target.value)} className="p-2 border rounded"><option>Dish</option>{dishes.map(x=><option key={x}>{x}</option>)}</select><input required value={ing} onChange={e=>setIng(e.target.value)} placeholder="Ingredient" className="p-2 border rounded"/><input required type="number" min=".001" step=".001" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Qty/tray" className="p-2 border rounded"/><div className="flex"><select value={unit} onChange={e=>setUnit(e.target.value)} className="p-2 border rounded flex-1">{UNITS.map(x=><option key={x}>{x}</option>)}</select><button className="px-3 bg-[#124E33] text-white rounded"><Plus/></button></div></form>{msg&&<div className="text-xs text-emerald-800 font-bold mt-2">{msg}</div>}</div>
  <div className="bg-blue-50 border border-blue-200 rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-sm uppercase flex items-center gap-2"><Calculator className="w-4 h-4"/> Suggested Production Ingredients</h3><p className="text-xs text-gray-600 mt-1">Estimated defaults only — edit before confirming actual consumption.</p></div><div className="flex gap-2 items-center text-xs"><select value={pkg} onChange={e=>setPkg(e.target.value)} className="p-2 border rounded bg-white"><option>VEG CLASSIC</option><option>EGG DELIGHT</option><option>NON-VEG CLUB</option></select><input type="number" min="1" step="1" value={suggestionThalis} onChange={e=>setSuggestionThalis(e.target.value)} className="w-20 p-2 border rounded bg-white"/><button onClick={generateSuggestions} className="px-3 py-2 bg-blue-600 text-white rounded-lg font-bold">Calculate</button></div></div>{suggested.length>0&&<div className="grid md:grid-cols-2 gap-2 mt-4">{suggested.map(s=>{const stock=findStock(s.ingredient);const available=stock?.currentStock??0;const shortage=Math.max(0,Number((s.quantity-available).toFixed(3)));return <div key={s.ingredient} className="bg-white border rounded-xl p-3 text-xs"><div className="flex justify-between"><b>{s.ingredient}</b><span className="text-gray-500">Suggested</span></div><div className="mt-1">Required: <b>{s.quantity} {s.unit}</b></div><div>Available: <b>{available} {stock?.unit||s.unit}</b></div>{shortage>0&&<div className="text-red-700 font-bold mt-1"><AlertTriangle className="inline w-3.5 h-3.5"/> Short by {shortage} {s.unit}</div>}</div>})}</div>}</div>
  <div className="bg-white border rounded-2xl p-5"><b className="text-sm">{pkg} / {meal} — {trays[pkg]||0} planned trays</b><div className="grid md:grid-cols-2 gap-2 mt-3">{list.map(r=><div key={r.id} className="border rounded-xl p-3 text-xs"><div className="flex justify-between"><b>{r.dish_name}</b><button onClick={()=>void remove(r.id)} className="text-red-600"><Trash2/></button></div><div>{r.ingredient_name}: <b>{r.quantity_per_tray} {r.unit}/tray</b></div><div className="text-emerald-800 font-bold">Total: {(Number(r.quantity_per_tray)*(trays[pkg]||0)).toLocaleString('en-IN')} {r.unit}</div></div>)}</div>{!list.length&&<p className="text-xs text-gray-500 mt-3">No saved recipe standard — use the suggested calculator above.</p>}</div>
 </div>;
}
