import React,{useMemo,useState} from 'react';
import {Printer,X} from 'lucide-react';
export const ReceiptPreview:React.FC<{indent:any;inventory:any[];onClose:()=>void}>=({indent,inventory,onClose})=>{
 const [supplier,setSupplier]=useState('Supplier / Vendor Name'),[contact,setContact]=useState(''),[address,setAddress]=useState(''),[gstin,setGstin]=useState(''),[invoice,setInvoice]=useState(''),[invoiceDate,setInvoiceDate]=useState(new Date().toISOString().slice(0,10)),[receivedDate,setReceivedDate]=useState(new Date().toISOString().slice(0,10)),[receivedBy,setReceivedBy]=useState('Kitchen Manager'),[store,setStore]=useState('Central Cloud Kitchen'),[notes,setNotes]=useState('');
 const [receivedQty,setReceivedQty]=useState(String(indent.receivedQuantity??indent.quantityNeeded??0)),[rate,setRate]=useState(String(indent.purchasePrice??inventory.find(x=>String(x.name).trim().toLowerCase()===String(indent.itemName).trim().toLowerCase())?.costPerUnit??0)),[tax,setTax]=useState('0');
 const grn=useMemo(()=>`GRN-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,[indent.id]);
 const qty=Number(receivedQty)||0, unit=indent.unit||'kg', price=Number(rate)||0, taxRate=Number(tax)||0, subtotal=qty*price, taxAmt=subtotal*taxRate/100, total=subtotal+taxAmt;
 return <div className="fixed inset-0 z-[70] bg-black/60 overflow-y-auto p-3 sm:p-6"><div className="max-w-5xl mx-auto bg-white rounded-2xl shadow-2xl">
 <div className="p-4 border-b flex items-center justify-between print:hidden"><div><b className="text-lg">Receipt / Goods Received Note (GRN)</b><p className="text-xs text-gray-500">Hotel / cloud-kitchen standard receiving document — demo preview</p></div><div className="flex gap-2"><button onClick={()=>window.print()} className="px-3 py-2 bg-[#124E33] text-white rounded-lg font-bold"><Printer className="inline w-4"/> Print / Save PDF</button><button onClick={onClose} className="p-2 border rounded-lg"><X/></button></div></div>
 <div className="grid lg:grid-cols-2 gap-4 p-4 border-b print:hidden text-xs">
 <label className="font-bold">Supplier / Vendor Name<input value={supplier} onChange={e=>setSupplier(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label><label className="font-bold">Contact / Extension<input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Phone / extension" className="w-full mt-1 p-2 border rounded"/></label>
 <label className="font-bold">Supplier Address<textarea value={address} onChange={e=>setAddress(e.target.value)} className="w-full mt-1 p-2 border rounded" rows={2}/></label><label className="font-bold">GSTIN<input value={gstin} onChange={e=>setGstin(e.target.value.toUpperCase())} className="w-full mt-1 p-2 border rounded"/></label>
 <label className="font-bold">Invoice / Bill No.<input value={invoice} onChange={e=>setInvoice(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label><label className="font-bold">Invoice Date<input type="date" value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label>
 <label className="font-bold">Goods Received Date<input type="date" value={receivedDate} onChange={e=>setReceivedDate(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label><label className="font-bold">Received By<input value={receivedBy} onChange={e=>setReceivedBy(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label>
 <label className="font-bold">Store / Kitchen<input value={store} onChange={e=>setStore(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label><label className="font-bold">Notes / Discrepancy<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="w-full mt-1 p-2 border rounded" rows={2}/></label>
 <div className="grid grid-cols-3 gap-2"><label className="font-bold">Received Qty<input type="number" min="0" step=".001" value={receivedQty} onChange={e=>setReceivedQty(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label><label className="font-bold">Rate / {unit}<input type="number" min="0" step=".01" value={rate} onChange={e=>setRate(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label><label className="font-bold">GST %<input type="number" min="0" step=".01" value={tax} onChange={e=>setTax(e.target.value)} className="w-full mt-1 p-2 border rounded"/></label></div>
 </div>
 <div className="p-7 sm:p-10"><div className="flex justify-between gap-5 border-b-2 pb-4"><div><div className="text-2xl font-black text-[#124E33]">BRING MY BITE</div><div className="text-xs text-gray-500">Central Cloud Kitchen • Goods Receiving Department</div></div><div className="text-right text-xs"><b>GOODS RECEIVED NOTE</b><div>GRN No: <b>{grn}</b></div><div>Received: <b>{receivedDate}</b></div></div></div>
 <div className="grid grid-cols-2 gap-6 mt-6 text-xs"><div><b>SUPPLIER / VENDOR</b><div className="mt-2 font-bold text-base">{supplier}</div><div>{address||'—'}</div><div>Contact / Extension: {contact||'—'}</div><div>GSTIN: {gstin||'—'}</div></div><div><b>RECEIVING DETAILS</b><div className="mt-2">Store / Kitchen: <b>{store}</b></div><div>Received By: <b>{receivedBy}</b></div><div>Invoice / Bill: <b>{invoice||'—'}</b></div><div>Invoice Date: <b>{invoiceDate||'—'}</b></div><div>PO / Indent Ref: <b>{indent.id}</b></div></div></div>
 <table className="w-full text-xs mt-7 border-collapse"><thead><tr className="bg-gray-100"><th className="border p-2 text-left">#</th><th className="border p-2 text-left">Item / Ingredient</th><th className="border p-2 text-right">Requested</th><th className="border p-2 text-right">Received</th><th className="border p-2">Unit</th><th className="border p-2 text-right">Rate</th><th className="border p-2 text-right">Amount</th></tr></thead><tbody><tr><td className="border p-2">1</td><td className="border p-2 font-bold">{indent.itemName}</td><td className="border p-2 text-right">{indent.quantityNeeded}</td><td className="border p-2 text-right font-bold">{qty}</td><td className="border p-2 text-center">{unit}</td><td className="border p-2 text-right">₹{price.toFixed(2)}</td><td className="border p-2 text-right">₹{subtotal.toFixed(2)}</td></tr></tbody></table>
 <div className="ml-auto w-64 mt-4 text-xs space-y-1"><div className="flex justify-between"><span>Subtotal</span><b>₹{subtotal.toFixed(2)}</b></div><div className="flex justify-between"><span>GST ({taxRate}%)</span><b>₹{taxAmt.toFixed(2)}</b></div><div className="flex justify-between border-t pt-2 text-sm"><span>Total Received Value</span><b>₹{total.toFixed(2)}</b></div></div>
 <div className="mt-5 text-xs"><b>Remarks:</b> {notes||'Goods physically received and checked against the purchase/indent record.'}</div><div className="grid grid-cols-3 gap-8 mt-16 text-xs text-center"><div className="border-t pt-2">Supplier / Delivery Person</div><div className="border-t pt-2">Received By</div><div className="border-t pt-2">Manager / Store Approval</div></div><div className="text-[10px] text-gray-400 text-center mt-8">This GRN records physical receipt. Inventory balance should be updated only for the quantity actually received.</div>
 </div></div></div>;
};