import React, { useState } from 'react';
import { Eye, EyeOff, LogIn, ShieldCheck } from 'lucide-react';
import { getSupabasePublishableKey, getSupabaseUrl, STAFF_SESSION_STORAGE_KEY } from '../../cms/supabaseRest';
import type { ActiveRole } from '../../types';

type StaffRouteRole = Exclude<ActiveRole, 'customer'>;
interface Props { role: StaffRouteRole; children: React.ReactNode; }
interface Session { role: StaffRouteRole; username: string; token: string; expires_at: number; }
const titles: Record<StaffRouteRole, string> = { admin: 'Admin', d_admin: 'D-Admin', manager: 'Manager', chef: 'Chef' };
export const SimpleStaffLogin: React.FC<Props> = ({ role, children }) => {
  const [session, setSession] = useState<Session | null>(() => { try { const saved = JSON.parse(localStorage.getItem(STAFF_SESSION_STORAGE_KEY) || 'null') as Session | null; return saved && saved.role === role && saved.expires_at > Date.now() ? saved : null; } catch { return null; } });
  const [username, setUsername] = useState(role === 'd_admin' ? 'dadmin' : role); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (session) return <>{children}</>;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!username.trim() || !password) { setError('Enter username and password.'); return; } setBusy(true); try { const response = await fetch(`${getSupabaseUrl()}/functions/v1/simple-staff-login`, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: getSupabasePublishableKey() }, body: JSON.stringify({ role, username: username.trim().toLowerCase(), password }) }); const data = await response.json().catch(() => ({})); if (!response.ok || data.role !== role || !data.token) throw new Error(data.error || 'Invalid username or password.'); const next: Session = { role, username: data.username, token: data.token, expires_at: Date.now() + Number(data.expires_in || 28800) * 1000 }; localStorage.setItem(STAFF_SESSION_STORAGE_KEY, JSON.stringify(next)); setPassword(''); setSession(next); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to sign in.'); } finally { setBusy(false); } };
  return <div className="min-h-[100dvh] bg-[#FAF7F2] flex items-center justify-center p-5"><form onSubmit={submit} className="w-full max-w-sm bg-white rounded-3xl border border-[#E5DAC6] shadow-xl p-6 space-y-5"><div className="text-center"><div className="mx-auto h-14 w-14 rounded-2xl bg-[#124E33] text-[#F2C94C] flex items-center justify-center"><ShieldCheck className="w-7 h-7" /></div><h1 className="mt-4 text-2xl font-black text-[#124E33]">{titles[role]} Login</h1><p className="mt-1 text-xs text-gray-500">Username and password only.</p></div><label className="block text-sm font-bold text-gray-700">Username<input autoFocus autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} className="mt-2 w-full rounded-xl border-2 border-gray-200 px-4 py-3 outline-none focus:border-[#124E33]" /></label><label className="block text-sm font-bold text-gray-700">Password<div className="relative mt-2"><input type={show ? 'text' : 'password'} autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} className="w-full rounded-xl border-2 border-gray-200 px-4 py-3 pr-12 outline-none focus:border-[#124E33]" /><button type="button" onClick={() => setShow(v => !v)} aria-label={show ? 'Hide password' : 'Show password'} className="absolute right-2 top-1/2 -translate-y-1/2 p-2">{show ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}</button></div></label>{error && <div className="rounded-xl bg-rose-50 border border-rose-200 p-3 text-xs font-semibold text-rose-800">{error}</div>}<button type="submit" disabled={busy || !username.trim() || !password} className="w-full rounded-xl bg-[#124E33] py-3.5 text-white font-black flex items-center justify-center gap-2 disabled:opacity-50"><LogIn className="w-4 h-4" />{busy ? 'Signing in…' : `Enter ${titles[role]} Panel`}</button></form></div>;
};
