import React, { useEffect, useMemo, useState } from 'react';
import { Calculator, Plus, Save, Trash2 } from 'lucide-react';
import { listStaffSalaries, saveStaffSalary, deleteStaffSalary, StaffSalaryRecord } from '../../utils/staffStore';

const input='w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-500';
const blank=():StaffSalaryRecord=>({id:`staff-${Date.now()}`,name:'',role:'chef',phone:'',monthlySalary:0,paymentDay:1,status:'Active',notes:'',updatedAt:new Date().toISOString()});

export const StaffFinancePanel: React.FC<{title?:string}> = ({title='Staff Salaries & Payroll'}) => {
 const [rows,setRows]=useState<StaffSalaryRecord[]>([]); const [draft,setDraft]=useState(blank());
 const load=async()=>setRows(await listStaffSalaries());
 useEffect(()=>{void load(); const fn=()=>void load(); window.addEventListener('bmb-staff-salary-change',fn); return()=>window.removeEventListener('bmb-staff-salary-change',fn);},[]);
 const total=useMemo(()=>rows.filter(x=>x.status==='Active').reduce((s,x)=>s+x.monthlySalary,0),[rows]);
 const save=async()=>{if(!draft.name.trim())return alert('Enter staff name.'); try{await saveStaffSalary({...draft,name:draft.name.trim(),updatedAt:new Date().toISOString()}); setDraft(blank()); await load(); alert('Saved successfully.');}catch(error){alert(error instanceof Error?error.message:'Unable to save staff record.');}};
 return <div className="space-y-4">
  <div className="bg-white rounded-2xl border border-gray-200 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-[#124E33]">{title}</h2><p className="text-sm text-gray-500">CEO/D-Admin and Admin can manage salaries for Admin, Manager, Chef and Chef Helpers.</p></div><div className="px-4 py-2 rounded-xl bg-emerald-50 text-emerald-800 text-sm font-black">Active payroll: ₹{total.toLocaleString()}</div></div>
   <div className="grid md:grid-cols-4 gap-3 mt-5"><input className={input} placeholder="Staff name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><select className={input} value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value as any})}><option value="admin">Admin</option><option value="manager">Manager</option><option value="chef">Chef</option><option value="chef-helper">Chef Helper</option><option value="other">Other</option></select><input className={input} placeholder="Phone" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/><input className={input} type="number" placeholder="Monthly salary" value={draft.monthlySalary} onChange={e=>setDraft({...draft,monthlySalary:Number(e.target.value)})}/><input className={input} type="number" min={1} max={31} placeholder="Payment day" value={draft.paymentDay} onChange={e=>setDraft({...draft,paymentDay:Number(e.target.value)})}/><select className={input} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as any})}><option>Active</option><option>Inactive</option></select><input className={input} placeholder="Notes / contract" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/><button onClick={save} className="rounded-xl bg-[#124E33] text-white font-black flex items-center justify-center gap-2"><Save className="w-4 h-4"/>Save Staff</button></div>
  </div>
  <div className="bg-white rounded-2xl border border-gray-200 p-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="text-left p-2">Name</th><th className="text-left p-2">Role</th><th className="text-left p-2">Phone</th><th className="text-right p-2">Salary</th><th className="text-center p-2">Pay Day</th><th className="text-center p-2">Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-gray-100"><td className="p-2 font-bold">{r.name}</td><td className="p-2">{r.role}</td><td className="p-2">{r.phone}</td><td className="p-2 text-right font-black">₹{r.monthlySalary.toLocaleString()}</td><td className="p-2 text-center">{r.paymentDay}</td><td className="p-2 text-center">{r.status}</td><td className="p-2 text-right"><button onClick={()=>setDraft(r)} className="px-2 py-1 rounded-lg bg-gray-100 text-xs font-bold mr-2">Edit</button><button onClick={async()=>{if(confirm('Delete this staff record?')){await deleteStaffSalary(r.id);await load();}}} className="text-rose-600"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>
 </div>;
};
