import { supabaseDelete, supabaseInsert, supabasePatch, supabaseSelect, isSupabaseConfigured } from '../cms/supabaseRest';
import { Subscription, InventoryItem, ChefIndentRequest, ReferralRecord } from '../types';

export const centralRequired=()=>{if(!isSupabaseConfigured)throw new Error('Central database is not configured.');};
const expiryFor=(startDate:string,duration:string)=>{const d=new Date(startDate||new Date().toISOString().slice(0,10));d.setMonth(d.getMonth()+(duration==='3 Months'?3:duration==='6 Months'?6:1));return d.toISOString().slice(0,10);};
const mapSubscription=(r:any):Subscription=>({id:r.id,customerName:r.customer_name??'',mobileNumber:r.mobile_number??'',whatsappNumber:r.whatsapp_number??'',dateOfBirth:r.date_of_birth,category:r.category,collegeName:r.college_name,courseSemester:r.course_semester,lunchDeliveryPoint:r.lunch_delivery_point,companyName:r.company_name,departmentDesignation:r.department_designation,houseFlatNo:r.house_flat_no,buildingSociety:r.building_society,streetArea:r.street_area,landmark:r.landmark,city:r.city,pinCode:r.pin_code,mapLocationLink:r.map_location_link,packageType:r.package_type,packageCode:r.package_code,monthlyPrice:Number(r.monthly_price??0),mealPreference:r.meal_preference,startDate:r.start_date,duration:r.duration,expiryDate:r.expiry_date,myReferralCode:r.my_referral_code,referredByCode:r.referred_by_code,complimentarySweetsEarnedWeeks:Number(r.complimentary_sweets_earned_weeks??0),biMonthlyBonusClaimed:r.bi_monthly_bonus_claimed??[],reminderSent3Days:Boolean(r.reminder_sent_3_days),renewedCount:Number(r.renewed_count??0),paymentMethod:r.payment_method,transactionId:r.transaction_id,amountPaid:Number(r.amount_paid??0),paymentDate:r.payment_date,verificationStatus:r.verification_status==='Approved'?'Approved':r.verification_status==='Rejected'?'Rejected':'Pending',routeCode:r.route_code,executiveName:r.executive_name,createdAt:r.created_at,active:Boolean(r.active),customFields:r.custom_fields??{}});
export async function listSubscriptions(){centralRequired();const rows=await supabaseSelect<any>('bmb_subscriptions','select=*&order=created_at.desc');return rows.map(mapSubscription);}
export async function insertSubscription(sub:any):Promise<Subscription>{centralRequired();const start=sub.startDate||new Date().toISOString().slice(0,10);const n:any={...sub,id:sub.id||`SUB-${Date.now()}`,startDate:start,expiryDate:sub.expiryDate||expiryFor(start,sub.duration),routeCode:sub.routeCode||`ROUTE-${Math.floor(100+Math.random()*900)}`,active:sub.active??true,verificationStatus:sub.verificationStatus||'Pending',createdAt:sub.createdAt||new Date().toISOString()};await supabaseInsert('bmb_subscriptions',{id:n.id,customer_name:n.customerName,mobile_number:n.mobileNumber,whatsapp_number:n.whatsappNumber||n.mobileNumber,category:n.category,college_name:n.collegeName,course_semester:n.courseSemester,lunch_delivery_point:n.lunchDeliveryPoint,company_name:n.companyName,department_designation:n.departmentDesignation,house_flat_no:n.houseFlatNo,building_society:n.buildingSociety,street_area:n.streetArea,landmark:n.landmark,city:n.city,pin_code:n.pinCode,map_location_link:n.mapLocationLink,package_type:n.packageType,package_code:n.packageCode,monthly_price:n.monthlyPrice,meal_preference:n.mealPreference,start_date:n.startDate,duration:n.duration,expiry_date:n.expiryDate,my_referral_code:n.myReferralCode,referred_by_code:n.referredByCode,complimentary_sweets_earned_weeks:n.complimentarySweetsEarnedWeeks??0,bi_monthly_bonus_claimed:n.biMonthlyBonusClaimed??[],reminder_sent_3_days:n.reminderSent3Days??false,renewed_count:n.renewedCount??0,payment_method:n.paymentMethod,transaction_id:n.transactionId,amount_paid:n.amountPaid,payment_date:n.paymentDate,verification_status:n.verificationStatus,route_code:n.routeCode,executive_name:n.executiveName,active:n.active,custom_fields:n.customFields??{},created_at:n.createdAt});return n as Subscription;}
export async function updateSubscription(id:string,patch:Record<string,unknown>){centralRequired();await supabasePatch('bmb_subscriptions',`id=eq.${encodeURIComponent(id)}`,{...patch,updated_at:new Date().toISOString()});}
export async function deleteSubscription(id:string){centralRequired();await supabaseDelete('bmb_subscriptions',`id=eq.${encodeURIComponent(id)}`);}
export async function listInventory():Promise<InventoryItem[]>{centralRequired();const rows=await supabaseSelect<any>('bmb_inventory','select=*&order=name.asc');return rows.map((r:any)=>({id:r.id,name:r.name??'',category:r.category,currentStock:Number(r.current_stock??0),unit:r.unit,minThreshold:Number(r.min_threshold??0),costPerUnit:Number(r.cost_per_unit??0),supplier:r.supplier??'',lastRestocked:r.last_restocked??'',status:r.status==='Critical'?'Critical':r.status==='Low Stock'?'Low Stock':'In Stock'}));}
export async function insertInventory(item:InventoryItem){centralRequired();await supabaseInsert('bmb_inventory',{id:item.id,name:item.name,category:item.category,current_stock:item.currentStock,unit:item.unit,min_threshold:item.minThreshold,cost_per_unit:item.costPerUnit,supplier:item.supplier,last_restocked:item.lastRestocked,status:item.status,updated_at:new Date().toISOString()});}
export async function updateInventory(id:string,currentStock:number,minThreshold:number){centralRequired();const stock=Math.max(0,currentStock);const status=stock<=0?'Critical':stock<=minThreshold?'Low Stock':'In Stock';await supabasePatch('bmb_inventory',`id=eq.${encodeURIComponent(id)}`,{current_stock:stock,status,updated_at:new Date().toISOString()});}
export async function listChefIndents():Promise<ChefIndentRequest[]>{centralRequired();const rows=await supabaseSelect<any>('bmb_chef_indents','select=*&order=requested_time.desc');return rows.map((r:any)=>({id:r.id,itemName:r.item_name??'',quantityNeeded:Number(r.quantity_needed??0),unit:r.unit??'',priority:r.priority,notes:r.notes??'',chefName:r.chef_name??'',requestedTime:r.requested_time,status:r.status,approvedBy:r.approved_by??undefined}));}
export async function insertChefIndent(indent:ChefIndentRequest){centralRequired();await supabaseInsert('bmb_chef_indents',{id:indent.id,item_name:indent.itemName,quantity_needed:indent.quantityNeeded,unit:indent.unit,priority:indent.priority,notes:indent.notes??'',chef_name:indent.chefName,requested_time:indent.requestedTime,status:indent.status,approved_by:indent.approvedBy??null,updated_at:new Date().toISOString()});}
export async function updateChefIndent(id:string,status:ChefIndentRequest['status'],approvedBy?:string){centralRequired();await supabasePatch('bmb_chef_indents',`id=eq.${encodeURIComponent(id)}`,{status,approved_by:approvedBy??null,updated_at:new Date().toISOString()});}
export async function listReferrals():Promise<ReferralRecord[]>{centralRequired();const rows=await supabaseSelect<any>('bmb_referrals','select=*&order=date_awarded.desc');return rows.map((r:any)=>({id:r.id,referrerCode:r.referrer_code,referrerName:r.referrer_name,referrerPhone:r.referrer_phone,referredCustomerName:r.referred_customer_name,referredCustomerId:r.referred_customer_id,reward:r.reward,rewardStatus:r.reward_status,dateAwarded:r.date_awarded}));}
export async function insertReferral(ref:ReferralRecord){centralRequired();await supabaseInsert('bmb_referrals',{id:ref.id,referrer_code:ref.referrerCode,referrer_name:ref.referrerName,referrer_phone:ref.referrerPhone,referred_customer_name:ref.referredCustomerName,referred_customer_id:ref.referredCustomerId,reward:ref.reward,reward_status:ref.rewardStatus,date_awarded:ref.dateAwarded,updated_at:new Date().toISOString()});}
