import { isSupabaseConfigured, supabaseSelect, supabaseInsert, supabasePatch, supabaseDelete, supabaseRpc } from '../cms/supabaseRest';
export type StoredOrderKind='instant'|'subscription';
export type StoredOrderStatus='Pending Verification'|'Confirmed'|'Preparing'|'Dispatched'|'Delivered'|'Cancelled'|'Rejected';
export type StoredPaymentStatus='Pending Verification'|'Verified'|'Rejected'|'Failed';
export interface StoredOrder{id:string;kind:StoredOrderKind;customerName:string;phone:string;whatsapp?:string;planOrMeal:string;amount:number;utrNumber:string;paymentSlip?:string;paymentStatus:StoredPaymentStatus;status:StoredOrderStatus;details?:string;createdAt:string;updatedAt:string;}
const KEY='bmb_order_requests_v1';
const readLocal=():StoredOrder[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};const writeLocal=(rows:StoredOrder[])=>{localStorage.setItem(KEY,JSON.stringify(rows));window.dispatchEvent(new Event('bmb-order-request-change'))};
export async function addStoredOrder(order:StoredOrder){if(!isSupabaseConfigured)throw new Error('Central database is not configured.');await supabaseInsert('bmb_orders',toDb(order) as any);writeLocal([order,...readLocal().filter(x=>x.id!==order.id)]);return order;}
export async function getStoredOrders(){if(!isSupabaseConfigured)return readLocal();try{const rows=await supabaseSelect<any>('bmb_orders','select=*&order=created_at.desc');const normalized=rows.map(normalizeRow);writeLocal(normalized);return normalized;}catch(e){console.warn('Central order read failed; using cached copy.',e);return readLocal();}}
export async function updateStoredOrder(id:string,patch:Partial<StoredOrder>){if(!isSupabaseConfigured)throw new Error('Central database is not configured.');await supabasePatch('bmb_orders',`id=eq.${encodeURIComponent(id)}`,toDbPatch(patch) as any);writeLocal(readLocal().map(o=>o.id===id?{...o,...patch,updatedAt:new Date().toISOString()}:o));}
export async function deleteStoredOrder(id:string){if(!isSupabaseConfigured)throw new Error('Central database is not configured.');await supabaseDelete('bmb_orders',`id=eq.${encodeURIComponent(id)}`);writeLocal(readLocal().filter(o=>o.id!==id));}
function toDb(order:StoredOrder){return{id:order.id,kind:order.kind,customer_name:order.customerName,phone:order.phone,whatsapp:order.whatsapp||'',plan_or_meal:order.planOrMeal,amount:order.amount,utr_number:order.utrNumber,payment_slip:order.paymentSlip||null,payment_status:order.paymentStatus,status:order.status,details:order.details||'',created_at:order.createdAt,updated_at:order.updatedAt};}
function toDbPatch(patch:Partial<StoredOrder>){const out:Record<string,unknown>={};if(patch.paymentStatus!==undefined)out.payment_status=patch.paymentStatus;if(patch.status!==undefined)out.status=patch.status;if(patch.details!==undefined)out.details=patch.details;if(patch.paymentSlip!==undefined)out.payment_slip=patch.paymentSlip;out.updated_at=new Date().toISOString();return out;}
function normalizeRow(r:any):StoredOrder{const status=r.status==='Approved'?'Confirmed':r.status==='Declined'?'Rejected':(r.status||'Pending Verification');return{id:r.id,kind:r.kind,customerName:r.customer_name??'',phone:r.phone??'',whatsapp:r.whatsapp??'',planOrMeal:r.plan_or_meal??'',amount:Number(r.amount??0),utrNumber:r.utr_number??'',paymentSlip:r.payment_slip??undefined,paymentStatus:r.payment_status==='Failed'?'Failed':(r.payment_status??'Pending Verification'),status,details:r.details??'',createdAt:r.created_at??new Date().toISOString(),updatedAt:r.updated_at??r.created_at??new Date().toISOString()};}
const TRACKING_KEY='bmb_last_order_tracking_v1';export function saveLastOrderTracking(order:Pick<StoredOrder,'id'|'phone'>){localStorage.setItem(TRACKING_KEY,JSON.stringify({id:order.id,phone:order.phone}));window.dispatchEvent(new Event('bmb-order-tracking-change'));}export function getLastOrderTracking(){try{return JSON.parse(localStorage.getItem(TRACKING_KEY)||'null')}catch{return null}}
export async function getPublicOrderStatus(id:string,phone:string){if(!isSupabaseConfigured){const l=readLocal().find(o=>o.id===id&&normalizePhone(o.phone)===normalizePhone(phone));return l?{id:l.id,paymentStatus:l.paymentStatus,status:l.status,updatedAt:l.updatedAt,details:l.details}:null}try{const rows=await supabaseRpc<any>('bmb_get_order_status',{p_order_id:id,p_phone:phone});const r=rows[0];if(!r)return null;return{id:r.id,paymentStatus:r.payment_status,status:r.status==='Approved'?'Confirmed':r.status==='Declined'?'Rejected':r.status,updatedAt:r.updated_at,details:r.details||''};}catch{return null;}}
function normalizePhone(v:string){return String(v||'').replace(/\D/g,'').slice(-10)}