import React, { createContext, useContext, useState, useEffect } from 'react';
import {
  Subscription, InstantOrder, DayMenuSchedule, InventoryItem, ChefIndentRequest, ActiveRole,
  ChatMessage, PackageType, ThaliType, ReferralRecord, BonusOffer
} from '../types';
import {
  INITIAL_INVENTORY, INITIAL_SUBSCRIPTIONS, INITIAL_INSTANT_ORDERS, INITIAL_CHEF_INDENTS,
  INITIAL_REFERRALS, BONUS_OFFERS
} from '../data/initialData';
import { useCms } from '../cms/CmsContext';
import { isSupabaseConfigured, signInWithStaffCredentials, signOut as supabaseSignOut, supabasePatch, supabaseDelete } from '../cms/supabaseRest';
import { subscribeToSupabaseChanges } from '../cms/supabaseRealtime';
import { getStoredOrders, updateStoredOrder } from '../utils/orderStore';
import { listSubscriptions, insertSubscription, listInventory, insertInventory, updateInventory, listChefIndents, insertChefIndent, updateChefIndent, listReferrals } from '../utils/centralData';

export interface PlanPricing { vegMonthly:number; eggMonthly:number; nonVegMonthly:number; vegThaliInstant:number; eggThaliInstant:number; nonVegThaliInstant:number; }
export const calculateExpiryDate=(startDate:string,duration:string):string=>{const start=new Date(startDate||new Date().toISOString().split('T')[0]);const months=duration==='3 Months'?3:duration==='6 Months'?6:1;const end=new Date(start);end.setMonth(end.getMonth()+months);return end.toISOString().split('T')[0];};
export const getDaysRemaining=(expiryDate:string):number=>{if(!expiryDate)return 30;const now=new Date();const end=new Date(expiryDate);return Math.ceil((end.getTime()-now.getTime())/(1000*60*60*24));};

interface AppContextType {
  activeRole: ActiveRole; setActiveRole:(role:ActiveRole)=>void; deviceType:'desktop'|'ios'|'android'; setDeviceType:(type:'desktop'|'ios'|'android')=>void;
  isStaffLoginOpen:boolean; setIsStaffLoginOpen:(open:boolean)=>void; targetStaffRole:'admin'|'manager'|'chef'|null; setTargetStaffRole:(role:'admin'|'manager'|'chef'|null)=>void;
  authenticatedRoles:{admin:boolean;manager:boolean;chef:boolean}; loginStaff:(role:'admin'|'manager'|'chef',pin:string)=>Promise<boolean>; logoutStaff:()=>void; openStaffLogin:(role?:'admin'|'manager'|'chef')=>void;
  isRegistrationOpen:boolean; setIsRegistrationOpen:(open:boolean)=>void; selectedPackageForRegistration:PackageType; setSelectedPackageForRegistration:(pkg:PackageType)=>void; isInstantOrderOpen:boolean; setIsInstantOrderOpen:(open:boolean)=>void;
  preselectedThaliType:ThaliType; setPreselectedThaliType:(type:ThaliType)=>void; isWeeklyMenuOpen:boolean; setIsWeeklyMenuOpen:(open:boolean)=>void; selectedMenuTab:PackageType; setSelectedMenuTab:(tab:PackageType)=>void;
  isChatOpen:boolean; setIsChatOpen:(open:boolean)=>void; activeBannerIndex:number; setActiveBannerIndex:(idx:number)=>void; isReferralModalOpen:boolean; setIsReferralModalOpen:(open:boolean)=>void;
  referrals:ReferralRecord[]; addReferralRecord:(referrerCode:string,newCustomerName:string,subId:string)=>boolean; isNativeAppModalOpen:boolean; setIsNativeAppModalOpen:(open:boolean)=>void;
  mobileTab:'home'|'menu'|'instant'|'subscribe'|'pass'|'portal'; setMobileTab:(tab:'home'|'menu'|'instant'|'subscribe'|'pass'|'portal')=>void; isPushEnabled:boolean; setIsPushEnabled:(enabled:boolean)=>void;
  isBonusOffersModalOpen:boolean; setIsBonusOffersModalOpen:(open:boolean)=>void; bonusOffers:BonusOffer[]; claimBonusOffer:(subId:string,bonusId:string)=>void;
  isRenewalModalOpen:boolean; setIsRenewalModalOpen:(open:boolean)=>void; selectedSubscriptionForRenewal:Subscription|null; setSelectedSubscriptionForRenewal:(sub:Subscription|null)=>void; renewSubscription:(subId:string,newDuration:string,amount:number)=>void;
  isReminderPreviewModalOpen:boolean; setIsReminderPreviewModalOpen:(open:boolean)=>void; activeReminderSubscription:Subscription|null; setActiveReminderSubscription:(sub:Subscription|null)=>void; sendSubscriptionReminder:(subId:string,channel:'whatsapp'|'sms'|'in_app')=>void; expiryBannerDismissed:boolean; setExpiryBannerDismissed:(dismissed:boolean)=>void;
  vegMenu:DayMenuSchedule[]; eggMenu:DayMenuSchedule[]; nonVegMenu:DayMenuSchedule[]; updateMenuItem:(packageType:PackageType,day:string,meal:'lunch'|'dinner',field:string,value:string)=>void;
  pricing:PlanPricing; updatePricing:(newPricing:Partial<PlanPricing>)=>void;
  subscriptions:Subscription[]; addSubscription:(sub:any)=>Promise<Subscription>; updateSubscriptionStatus:(id:string,status:'Approved'|'Pending'|'Rejected',routeCode?:string,execName?:string)=>Promise<void>; deleteSubscription:(id:string)=>Promise<void>;
  instantOrders:InstantOrder[]; addInstantOrder:(order:any)=>InstantOrder; updateOrderStatus:(id:string,status:InstantOrder['status'])=>Promise<void>;
  inventory:InventoryItem[]; updateInventoryStock:(id:string,newStock:number)=>Promise<void>; addNewInventoryItem:(item:any)=>Promise<void>; restockItem:(id:string,quantityToAdd:number)=>Promise<void>;
  chefIndents:ChefIndentRequest[]; addChefIndent:(indent:any)=>Promise<void>; updateChefIndentStatus:(id:string,status:ChefIndentRequest['status'],approvedBy?:string)=>Promise<void>;
  chatMessages:ChatMessage[]; sendChatMessage:(text:string)=>void;
  todayMealsCount:{lunchVeg:number;lunchEgg:number;lunchNonVeg:number;dinnerVeg:number;dinnerEgg:number;dinnerNonVeg:number;totalToday:number;totalRotiLunch:number;totalRotiDinner:number};
  totalRevenue:number; totalSubscribers:number; lowStockCount:number; pendingIndentsCount:number; expiringSoonCount:number; totalReferralsCount:number;
}
const AppContext=createContext<AppContextType|undefined>(undefined);

export const AppProvider:React.FC<{children:React.ReactNode}>=({children})=>{
  const cms=useCms();
  const [activeRole,setActiveRole]=useState<ActiveRole>('customer');
  const [deviceType,setDeviceType]=useState<'desktop'|'ios'|'android'>('desktop');
  const [isStaffLoginOpen,setIsStaffLoginOpen]=useState(false);
  const [targetStaffRole,setTargetStaffRole]=useState<'admin'|'manager'|'chef'|null>(null);
  const [authenticatedRoles,setAuthenticatedRoles]=useState({admin:false,manager:false,chef:false});
  const loginStaff=async(role:'admin'|'manager'|'chef',pin:string)=>{if(!isSupabaseConfigured||!/^[0-9]{6}$/.test(pin.trim()))return false;try{const session=await signInWithStaffCredentials(role,pin);if(session.role!==role)return false;const next={...authenticatedRoles,[role]:true};setAuthenticatedRoles(next);setActiveRole(role);setIsStaffLoginOpen(false);setTargetStaffRole(null);localStorage.setItem('bmb_staff_auth_roles',JSON.stringify(next));window.dispatchEvent(new CustomEvent('bmb:staff-authenticated',{detail:{role,userId:session.id,username:session.username}}));return true;}catch{return false;}};
  const logoutStaff=()=>{supabaseSignOut();setAuthenticatedRoles({admin:false,manager:false,chef:false});setActiveRole('customer');window.dispatchEvent(new CustomEvent('bmb:staff-logout'));};
  const openStaffLogin=(role?:'admin'|'manager'|'chef')=>{if(role)setTargetStaffRole(role);setIsStaffLoginOpen(true);};
  const [isRegistrationOpen,setIsRegistrationOpen]=useState(false),[selectedPackageForRegistration,setSelectedPackageForRegistration]=useState<PackageType>('VEG CLASSIC'),[isInstantOrderOpen,setIsInstantOrderOpen]=useState(false),[preselectedThaliType,setPreselectedThaliType]=useState<ThaliType>('veg'),[isWeeklyMenuOpen,setIsWeeklyMenuOpen]=useState(false),[selectedMenuTab,setSelectedMenuTab]=useState<PackageType>('VEG CLASSIC'),[isChatOpen,setIsChatOpen]=useState(false),[activeBannerIndex,setActiveBannerIndex]=useState(0);
  const [isReferralModalOpen,setIsReferralModalOpen]=useState(false),[isBonusOffersModalOpen,setIsBonusOffersModalOpen]=useState(false),[isRenewalModalOpen,setIsRenewalModalOpen]=useState(false),[selectedSubscriptionForRenewal,setSelectedSubscriptionForRenewal]=useState<Subscription|null>(null),[isReminderPreviewModalOpen,setIsReminderPreviewModalOpen]=useState(false),[activeReminderSubscription,setActiveReminderSubscription]=useState<Subscription|null>(null),[expiryBannerDismissed,setExpiryBannerDismissed]=useState(false);
  const [isNativeAppModalOpen,setIsNativeAppModalOpen]=useState(false),[mobileTab,setMobileTab]=useState<'home'|'menu'|'instant'|'subscribe'|'pass'|'portal'>('home'),[isPushEnabled,setIsPushEnabled]=useState(true);
  const vegMenu=cms.menus['VEG CLASSIC'],eggMenu=cms.menus['EGG DELIGHT'],nonVegMenu=cms.menus['NON-VEG CLUB'],pricing=cms.pricing;
  const [subscriptions,setSubscriptions]=useState<Subscription[]>([]),[referrals,setReferrals]=useState<ReferralRecord[]>([]),[instantOrders,setInstantOrders]=useState<InstantOrder[]>([]),[inventory,setInventory]=useState<InventoryItem[]>([]),[chefIndents,setChefIndents]=useState<ChefIndentRequest[]>([]); const [bonusOffers]=useState<BonusOffer[]>(BONUS_OFFERS);
  const loadData=async()=>{if(!isSupabaseConfigured){setSubscriptions(INITIAL_SUBSCRIPTIONS);setReferrals(INITIAL_REFERRALS);setInstantOrders(INITIAL_INSTANT_ORDERS);setInventory(INITIAL_INVENTORY);setChefIndents(INITIAL_CHEF_INDENTS);return;}try{const [subs,inv,indents,orders,refs]=await Promise.all([listSubscriptions(),listInventory(),listChefIndents(),getStoredOrders(),listReferrals()]);setSubscriptions(subs);setInventory(inv);setChefIndents(indents);setInstantOrders(orders.filter(o=>o.kind==='instant').map(o=>({id:o.id,customerName:o.customerName,customerPhone:o.phone,thaliType:(o.planOrMeal.toLowerCase().includes('egg')?'egg':o.planOrMeal.toLowerCase().includes('non-veg')?'non-veg':'veg') as ThaliType,thaliName:o.planOrMeal,quantity:1,unitPrice:o.amount,totalPrice:o.amount,mealSlot:o.planOrMeal.toLowerCase().includes('dinner')?'Dinner':'Lunch',deliveryCategory:'Other',deliveryLocation:o.details??'',status:o.status==='Confirmed'?'Received':o.status==='Rejected'?'Cancelled':o.status==='Preparing'?'Cooking':o.status as any,paymentMethod:'UPI',paymentStatus:o.paymentStatus==='Verified'?'Prepaid Verified':o.paymentStatus==='Rejected'?'Paid':'Pending Verification',orderTime:o.createdAt,estimatedDelivery:o.createdAt})));setReferrals(refs);}catch(e){console.warn('Central data load failed',e);}};
  useEffect(()=>{void loadData(); if(!isSupabaseConfigured)return; const unsubscribe=subscribeToSupabaseChanges(['bmb_subscriptions','bmb_orders','bmb_inventory','bmb_chef_indents','bmb_referrals'],()=>{void loadData();}); const fallback=window.setInterval(()=>void loadData(),60000); return()=>{unsubscribe();window.clearInterval(fallback);};},[]);
  const updatePricing=(values:Partial<PlanPricing>)=>void cms.updatePricing(values);
  const updateMenuItem=async(packageType:PackageType,day:string,meal:'lunch'|'dinner',field:string,value:any)=>{const schedule=cms.menus[packageType]??[];const next=schedule.map(s=>s.day===day?{...s,[meal]:meal==='lunch'?{...s.lunch,[field]:value}:{...(s.dinner||{dal:'',dryVeg:'',gravyOrNonVeg:'',rice:'',foilPacked:'',extras:''}),[field]:value}}:s);await cms.saveMenu(packageType,next);};
  const addSubscription=async(sub:any)=>{const normalized:any={...sub,id:sub.id||`SUB-${Date.now()}`,expiryDate:sub.expiryDate||calculateExpiryDate(sub.startDate,sub.duration),routeCode:sub.routeCode||`ROUTE-${Math.floor(100+Math.random()*900)}`,active:sub.active??true,createdAt:sub.createdAt||new Date().toISOString(),verificationStatus:sub.verificationStatus||'Pending'};const saved=await insertSubscription(normalized);setSubscriptions(prev=>[saved,...prev]);return saved;};
  const updateSubscriptionStatus=async(id:string,status:'Approved'|'Pending'|'Rejected',routeCode?:string,execName?:string)=>{await supabasePatch('bmb_subscriptions',`id=eq.${encodeURIComponent(id)}`,{verification_status:status,route_code:routeCode,executive_name:execName,updated_at:new Date().toISOString()});setSubscriptions(prev=>prev.map(s=>s.id===id?{...s,verificationStatus:status,routeCode:routeCode??s.routeCode,executiveName:execName??s.executiveName}:s));};
  const deleteSubscription=async(id:string)=>{await supabaseDelete('bmb_subscriptions',`id=eq.${encodeURIComponent(id)}`);setSubscriptions(prev=>prev.filter(s=>s.id!==id));};
  const addInstantOrder=(order:any)=>{const normalized:any={...order,id:order.id||`ORD-${Date.now()}`,orderTime:order.orderTime||new Date().toISOString(),estimatedDelivery:order.estimatedDelivery||new Date(Date.now()+60*60000).toISOString()};setInstantOrders(prev=>[normalized,...prev]);return normalized;};
  const updateOrderStatus=async(id:string,status:InstantOrder['status'])=>{const central=status==='Received'?'Confirmed':status==='Cooking'?'Preparing':status==='Cancelled'?'Cancelled':status==='Delivered'?'Delivered':status==='Dispatched'?'Dispatched':'Pending Verification';await updateStoredOrder(id,{status:central as any,paymentStatus:central==='Confirmed'||central==='Preparing'||central==='Dispatched'||central==='Delivered'?'Verified':undefined} as any);setInstantOrders(prev=>prev.map(o=>o.id===id?{...o,status}:o));};
  const updateInventoryStock=async(id:string,newStock:number)=>{const item=inventory.find(x=>x.id===id);if(!item)throw new Error('Inventory item not found.');await updateInventory(id,newStock,item.minThreshold);const safe=Math.max(0,newStock),status=safe<=0?'Critical':safe<=item.minThreshold?'Low Stock':'In Stock';setInventory(prev=>prev.map(x=>x.id===id?{...x,currentStock:safe,status}:x));};
  const addNewInventoryItem=async(item:any)=>{const normalized:InventoryItem={id:item.id||`INV-${Date.now()}`,name:item.name,category:item.category==='Grains'?'Grains & Pulses':item.category==='Dairy'||item.category==='Poultry'?'Dairy & Poultry':item.category==='Vegetables'?'Fresh Vegetables':item.category==='Spices'?'Spices & Oils':'Packaging & Consumables',currentStock:Number(item.quantity??item.currentStock??0),unit:item.unit,minThreshold:Number(item.reorderThreshold??item.minThreshold??0),costPerUnit:Number(item.costPerUnit??0),supplier:item.supplier??'',lastRestocked:item.lastRestocked||new Date().toISOString().slice(0,10),status:'In Stock'};await insertInventory(normalized);setInventory(prev=>[normalized,...prev]);};
  const restockItem=async(id:string,quantityToAdd:number)=>{const item=inventory.find(x=>x.id===id);if(!item)throw new Error('Inventory item not found.');await updateInventoryStock(id,item.currentStock+quantityToAdd);};
  const addChefIndent=async(indent:any)=>{const normalized:ChefIndentRequest={id:indent.id||`IND-${Date.now()}`,itemName:indent.itemName??indent.ingredientName,quantityNeeded:Number(indent.quantityNeeded??indent.quantity??0),unit:indent.unit??'kg',priority:indent.priority==='Urgent'?'Urgent (Today)':indent.priority==='Regular'?'Standard (Tomorrow)':indent.priority??'Weekly Buffer',notes:indent.notes,chefName:indent.chefName??'Chef',requestedTime:indent.requestedTime||new Date().toISOString(),status:indent.status==='Pending'?'Pending Approval':indent.status??'Pending Approval',approvedBy:indent.approvedBy};await insertChefIndent(normalized);setChefIndents(prev=>[normalized,...prev]);};
  const updateChefIndentStatus=async(id:string,status:ChefIndentRequest['status'],approvedBy?:string)=>{await import('../utils/centralData').then(m=>m.updateChefIndent(id,status,approvedBy));setChefIndents(prev=>prev.map(x=>x.id===id?{...x,status,approvedBy}:x));};
  const addReferralRecord=()=>false; const claimBonusOffer=()=>{}; const renewSubscription=()=>{}; const sendSubscriptionReminder=()=>{}; const sendChatMessage=(text:string)=>{if(text.trim())setChatMessages(prev=>[...prev,{id:`msg-${Date.now()}`,sender:'user',text,timestamp:'Just now'}]);}; const [chatMessages,setChatMessages]=useState<ChatMessage[]>([{id:'msg-1',sender:'bot',text:'Namaste! 🙏 Welcome to Bring My Bite by Shree Foods. How can we help you today?',timestamp:'Just now',suggestions:['What is in today\'s Lunch?','How does College Gate delivery work?','How much is the Monthly Veg Plan?','Referral Sweets Offer 🍬']}]);
  const totalRevenue=subscriptions.reduce((sum,s)=>sum+(s.amountPaid||0),0)+instantOrders.reduce((sum,o)=>sum+(o.totalPrice||0),0),totalSubscribers=subscriptions.filter(s=>s.active).length,lowStockCount=inventory.filter(i=>i.currentStock<=i.minThreshold).length,pendingIndentsCount=chefIndents.filter(i=>i.status==='Pending Approval').length,expiringSoonCount=subscriptions.filter(s=>s.active&&getDaysRemaining(s.expiryDate)<=3).length,totalReferralsCount=referrals.length; const todayMealsCount={lunchVeg:0,lunchEgg:0,lunchNonVeg:0,dinnerVeg:0,dinnerEgg:0,dinnerNonVeg:0,totalToday:0,totalRotiLunch:0,totalRotiDinner:0};
  return <AppContext.Provider value={{activeRole,setActiveRole,deviceType,setDeviceType,isStaffLoginOpen,setIsStaffLoginOpen,targetStaffRole,setTargetStaffRole,authenticatedRoles,loginStaff,logoutStaff,openStaffLogin,isRegistrationOpen,setIsRegistrationOpen,selectedPackageForRegistration,setSelectedPackageForRegistration,isInstantOrderOpen,setIsInstantOrderOpen,preselectedThaliType,setPreselectedThaliType,isWeeklyMenuOpen,setIsWeeklyMenuOpen,selectedMenuTab,setSelectedMenuTab,isChatOpen,setIsChatOpen,activeBannerIndex,setActiveBannerIndex,isReferralModalOpen,setIsReferralModalOpen,referrals,addReferralRecord,isNativeAppModalOpen,setIsNativeAppModalOpen,mobileTab,setMobileTab,isPushEnabled,setIsPushEnabled,isBonusOffersModalOpen,setIsBonusOffersModalOpen,bonusOffers,claimBonusOffer,isRenewalModalOpen,setIsRenewalModalOpen,selectedSubscriptionForRenewal,setSelectedSubscriptionForRenewal,renewSubscription,isReminderPreviewModalOpen,setIsReminderPreviewModalOpen,activeReminderSubscription,setActiveReminderSubscription,sendSubscriptionReminder,expiryBannerDismissed,setExpiryBannerDismissed,vegMenu,eggMenu,nonVegMenu,updateMenuItem,pricing,updatePricing,subscriptions,addSubscription,updateSubscriptionStatus,deleteSubscription,instantOrders,addInstantOrder,updateOrderStatus,inventory,updateInventoryStock,addNewInventoryItem,restockItem,chefIndents,addChefIndent,updateChefIndentStatus,chatMessages,sendChatMessage,todayMealsCount,totalRevenue,totalSubscribers,lowStockCount,pendingIndentsCount,expiringSoonCount,totalReferralsCount}}>{children}</AppContext.Provider>;
};
export const useApp=()=>{const ctx=useContext(AppContext);if(!ctx)throw new Error('useApp must be used within AppProvider');return ctx;};