alter table public.bmb_chef_indents
  add column if not exists payment_status text not null default 'Not Submitted',
  add column if not exists payment_request_id text,
  add column if not exists payment_approved_by text,
  add column if not exists payment_approved_at timestamptz,
  add column if not exists payment_rejection_note text;

create table if not exists public.bmb_inventory_purchase_requests (
  id text primary key,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  status text not null default 'Pending Admin Approval' check (status in ('Pending Admin Approval','Approved','Rejected')),
  requested_by text not null default 'Manager',
  requested_at timestamptz not null default now(),
  reviewed_by text,
  reviewed_at timestamptz,
  rejection_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bmb_inventory_purchase_request_lines (
  id bigint generated by default as identity primary key,
  request_id text not null references public.bmb_inventory_purchase_requests(id) on delete cascade,
  indent_id text not null references public.bmb_chef_indents(id) on delete restrict,
  item_name text not null,
  quantity numeric(12,3) not null check (quantity > 0),
  unit text not null,
  purchase_price numeric(12,2) not null check (purchase_price > 0),
  line_total numeric(12,2) not null check (line_total > 0),
  created_at timestamptz not null default now(),
  unique(request_id, indent_id)
);

create index if not exists bmb_inventory_purchase_requests_status_idx on public.bmb_inventory_purchase_requests(status, requested_at desc);
create index if not exists bmb_inventory_purchase_request_lines_request_idx on public.bmb_inventory_purchase_request_lines(request_id);

alter table public.bmb_inventory_purchase_requests enable row level security;
alter table public.bmb_inventory_purchase_request_lines enable row level security;

drop policy if exists bmb_public_full_access on public.bmb_inventory_purchase_requests;
create policy bmb_public_full_access on public.bmb_inventory_purchase_requests for all to anon, authenticated using (true) with check (true);

drop policy if exists bmb_public_full_access on public.bmb_inventory_purchase_request_lines;
create policy bmb_public_full_access on public.bmb_inventory_purchase_request_lines for all to anon, authenticated using (true) with check (true);
